version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: /run/secrets/postgres_db
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - appnet
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.role == db
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U names_user -d namesdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  api:
    image: localhost/names-backend:latest
    environment:
      DATABASE_URL: postgresql+psycopg2://names_user:names_pass@db:5432/namesdb
      MAX_NAME_LENGTH: "50"
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: "8000"
      LOG_LEVEL: INFO
      DB_ECHO: "false"
    networks:
      - appnet
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 10s
    depends_on:
      - db

  web:
    image: localhost/names-frontend:latest
    ports:
      - "80:80"
    networks:
      - appnet
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
    depends_on:
      - api

networks:
  appnet:
    external: true

volumes:
  dbdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/lib/postgres-data

secrets:
  postgres_user:
    external: true
  postgres_password:
    external: true
  postgres_db:
    external: true
